### ISSUE TITLE
Error: Cannot find module 'head_ct_4_features/index.json'

### ISSUE THREAD

**Issue by gaaguile** [Kitware/arctic-viewer#32]
Hi, Please could someone help me. I downloaded and uncompressed one example. 
But it seems there is something wrong with the file "index.json" on the head_ct4_features directory.

[0 Sun May 13 20:36:03 903 ~/sample-data 0 ]$ ArcticViewer -d head_ct_4_features
module.js:549
    throw err;
    ^

Error: Cannot find module 'head_ct_4_features/index.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at processDirectory (/usr/local/lib/node_modules/arctic-viewer/bin/arctic-dataset-list-builder.js:74:31)
    at Function.app.updateDataPath (/usr/local/lib/node_modules/arctic-viewer/bin/server.js:117:7)
    at module.exports (/usr/local/lib/node_modules/arctic-viewer/bin/server.js:135:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/arctic-viewer/bin/arctic-viewer-cli.js:58:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
[0 Sun May 13 20:36:18 904 ~/sample-data 0 ]$

**Comment by jourdain** [comment]
Provide a full path to the dataset. Maybe `./head_ct_4_features` could be enough.

**Comment by gaaguile** [comment]
thank you, Sebastien. Now it's running!
